.Dd $Mdocdate: November 29 2007 $
.Dt FLASHPOLICYSERV 8
.Os
.Sh NAME
.Nm flashpolicyserv
.Nd
.Tn simple Flash socket policy server
.Sh SYNOPSIS
.Nm flashpolicyserv
.Op Fl f Ar file
.Op Fl p Ar port
.Op Fl u Ar user
.Op Fl c Ar directory
.Sh DESCRIPTION
.Nm
is a simple daemon serving XML socket policy files to Flash clients.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar file
Serve the XML policy from
.Ar file .
Default: /etc/flash_policy.xml.
You have to restart the daemon in order to reload the file.
.It Fl p Ar port
Listen on
.Ar port .
Default: 843.
.It Fl u Ar user
Drop privileges for
.Ar user
on startup. Default: nobody.
.It Fl c Ar directory
.Xr chroot 2
to
.Ar directory
on starturp. Default: /var/run.
.El
.Sh SEE ALSO
.Xr http://www.adobe.com/devnet/flashplayer/articles/fplayer9_security.html ,
.Xr http://www.adobe.com/devnet/flashplayer/articles/socket_policy_files.html
.Sh HISTORY
The
.Nm
command appeared in 2011.
